services:
  - type: web
    name: bvg-sbahn-bot
    env: python
    plan: free
    region: frankfurt

    buildCommand: |
      pip install -r requirements.txt
      playwright install

    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright
      - key: TWITTER_USERNAME
        sync: false
      - key: TWITTER_PASSWORD
        sync: false
      - key: TWITTER_EMAIL
        sync: false
