services:
  - type: web
    name: bvg-sbahn-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps firefox
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: TWITTER_USER
        sync: false
      - key: TWITTER_PASS
        sync: false
