services:
  - type: web
    name: bvg-sbahn-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DISCORD_WEBHOOK
        sync: false  # damit Render es im Dashboard setzt, nicht im Repo sichtbar
